In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("uncleaned_DS_jobs.csv")

print("Shape: " + str(df.shape))
print("Columns: " + str(df.columns.tolist()))

Shape: (672, 15)
Columns: ['index', 'Job Title', 'Salary Estimate', 'Job Description', 'Rating', 'Company Name', 'Location', 'Headquarters', 'Size', 'Founded', 'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors']

In [3]:
#Explore the data
df.head(10)

,index,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Sr Data Scientist,$137K-$171K (Glassdoor est.),Description\n\nThe Senior Data Scientist is re...,3.1,Healthfirst\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna"
1,1,Data Scientist,$137K-$171K (Glassdoor est.),"Secure our Nation, Ignite your Future\n\nJoin ...",4.2,ManTech\n4.2,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1
2,2,Data Scientist,$137K-$171K (Glassdoor est.),Overview\n\n\nAnalysis Group is one of the lar...,3.8,Analysis Group\n3.8,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$137K-$171K (Glassdoor est.),JOB DESCRIPTION:\n\nDo you have a passion for ...,3.5,INFICON\n3.5,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,4,Data Scientist,$137K-$171K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"
5,5,Data Scientist,$137K-$171K (Glassdoor est.),About Us:\n\nHeadquartered in beautiful Santa ...,4.2,HG Insights\n4.2,"Santa Barbara, CA","Santa Barbara, CA",51 to 200 employees,2010,Company - Private,Computer Hardware & Software,Information Technology,Unknown / Non-Applicable,-1
6,6,Data Scientist / Machine Learning Expert,$137K-$171K (Glassdoor est.),Posting Title\nData Scientist / Machine Learni...,3.9,Novartis\n3.9,"Cambridge, MA","Basel, Switzerland",10000+ employees,1996,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$10+ billion (USD),-1
7,7,Data Scientist,$137K-$171K (Glassdoor est.),Introduction\n\nHave you always wanted to run ...,3.5,iRobot\n3.5,"Bedford, MA","Bedford, MA",1001 to 5000 employees,1990,Company - Public,Consumer Electronics & Appliances Stores,Retail,$1 to $2 billion (USD),-1
8,8,Staff Data Scientist - Analytics,$137K-$171K (Glassdoor est.),Intuit is seeking a Staff Data Scientist to co...,4.4,Intuit - Data\n4.4,"San Diego, CA","Mountain View, CA",5001 to 10000 employees,1983,Company - Public,Computer Hardware & Software,Information Technology,$2 to $5 billion (USD),"Square, PayPal, H&R Block"
9,9,Data Scientist,$137K-$171K (Glassdoor est.),Ready to write the best chapter of your career...,3.6,XSELL Technologies\n3.6,"Chicago, IL","Chicago, IL",51 to 200 employees,2014,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1

In [4]:
#Check data type and missing Values
print(df.dtypes)
print(df.isnull().sum())

index                  int64
Job Title             object
Salary Estimate       object
Job Description       object
Rating               float64
Company Name          object
Location              object
Headquarters          object
Size                  object
Founded                int64
Type of ownership     object
Industry              object
Sector                object
Revenue               object
Competitors           object
dtype: object
index                0
Job Title            0
Salary Estimate      0
Job Description      0
Rating               0
Company Name         0
Location             0
Headquarters         0
Size                 0
Founded              0
Type of ownership    0
Industry             0
Sector               0
Revenue              0
Competitors          0
dtype: int64

In [5]:
#Rename Columns
#Check current column names
print("Current columns:",df.columns.tolist())

#Rename columns - remove spaces and make lowercase

df.columns =df.columns.str.strip().str.lower().str.replace(" ", "_")
print("\nRename columns:")
print(df.columns.tolist())

Current columns: ['index', 'Job Title', 'Salary Estimate', 'Job Description', 'Rating', 'Company Name', 'Location', 'Headquarters', 'Size', 'Founded', 'Type of ownership', 'Industry', 'Sector', 'Revenue', 'Competitors']

Rename columns:
['index', 'job_title', 'salary_estimate', 'job_description', 'rating', 'company_name', 'location', 'headquarters', 'size', 'founded', 'type_of_ownership', 'industry', 'sector', 'revenue', 'competitors']

In [6]:
print(df["salary_estimate"].unique()[:5])

['$137K-$171K (Glassdoor est.)' '$75K-$131K (Glassdoor est.)'
 '$79K-$131K (Glassdoor est.)' '$99K-$132K (Glassdoor est.)'
 '$90K-$109K (Glassdoor est.)']

In [7]:
df["salary_estimate"] = df["salary_estimate"].str.replace("(Glassdoor est.)","",regex=False)
print(df["salary_estimate"].unique()[:5])

['$137K-$171K ' '$75K-$131K ' '$79K-$131K ' '$99K-$132K ' '$90K-$109K ']

In [8]:
df["salary_estimate"] = df["salary_estimate"].str.strip()
print(df["salary_estimate"].unique()[:5])

['$137K-$171K' '$75K-$131K' '$79K-$131K' '$99K-$132K' '$90K-$109K']

In [9]:
df["salary_estimate"] = df["salary_estimate"].str.replace("$","",regex= False)

In [10]:
print(df["salary_estimate"].unique()[:5])

['137K-171K' '75K-131K' '79K-131K' '99K-132K' '90K-109K']

In [11]:
df["salary_estimate"] = df["salary_estimate"].str.replace("K","000",regex=False)
print(df["salary_estimate"].unique()[:5])

['137000-171000' '75000-131000' '79000-131000' '99000-132000'
 '90000-109000']

In [12]:
df[["min_salary", "max_salary"]] = df["salary_estimate"].str.split("-", expand=True)
print(df[["min_salary", "max_salary"]].head())

  min_salary max_salary
0     137000     171000
1     137000     171000
2     137000     171000
3     137000     171000
4     137000     171000

In [13]:
print(df["company_name"].unique()[:5])

['Healthfirst\n3.1' 'ManTech\n4.2' 'Analysis Group\n3.8' 'INFICON\n3.5'
 'Affinity Solutions\n2.9']

In [14]:
df["company_name"] = df["company_name"].str.split("\n").str[0]
print(df["company_name"].head())

0           Healthfirst
1               ManTech
2        Analysis Group
3               INFICON
4    Affinity Solutions
Name: company_name, dtype: object

In [15]:
print(df["job_description"].unique()[:5])

["Description\n\nThe Senior Data Scientist is responsible for defining, building, and improving statistical models to improve business processes and outcomes in one or more healthcare domains such as Clinical, Enrollment, Claims, and Finance. As part of the broader analytics team, Data Scientist will gather and analyze data to solve and address complex business problems and evaluate scenarios to make predictions on future outcomes and work with the business to communicate and support decision-making. This position requires strong analytical skills and experience in analytic methods including multivariate regressions, hierarchical linear models, regression trees, clustering methods and other complex statistical techniques.\n\nDuties & Responsibilities:\n\n• Develops advanced statistical models to predict, quantify or forecast various operational and performance metrics in multiple healthcare domains\n• Investigates, recommends, and initiates acquisition of new data resources from internal and external sources\n• Works with multiple teams to support data collection, integration, and retention requirements based on business needs\n• Identifies critical and emerging technologies that will support and extend quantitative analytic capabilities\n• Collaborates with business subject matter experts to select relevant sources of information\n• Develops expertise with multiple machine learning algorithms and data science techniques, such as exploratory data analysis and predictive modeling, graph theory, recommender systems, text analytics and validation\n• Develops expertise with Healthfirst datasets, data repositories, and data movement processes\n• Assists on projects/requests and may lead specific tasks within the project scope\n• Prepares and manipulates data for use in development of statistical models\n• Other duties as assigned\n\nMinimum Qualifications:\n\n-Bachelor's Degree\n\nPreferred Qualifications:\n\n- Master’s degree in Computer Science or Statistics\nFamiliarity with major cloud platforms such as AWS and Azure\nHealthcare Industry Experience\n\nMinimum Qualifications:\n\n-Bachelor's Degree\n\nPreferred Qualifications:\n\n- Master’s degree in Computer Science or Statistics\nFamiliarity with major cloud platforms such as AWS and Azure\nHealthcare Industry Experience\n\nWE ARE AN EQUAL OPPORTUNITY EMPLOYER. Applicants and employees are considered for positions and are evaluated without regard to mental or physical disability, race, color, religion, gender, national origin, age, genetic information, military or veteran status, sexual orientation, marital status or any other protected Federal, State/Province or Local status unrelated to the performance of the work involved.\n\nIf you have a disability under the Americans with Disability Act or a similar law, and want a reasonable accommodation to assist with your job search or application for employment, please contact us by sending an email to careers@Healthfirst.org or calling 212-519-1798 . In your email please include a description of the accommodation you are requesting and a description of the position for which you are applying. Only reasonable accommodation requests related to applying for a position within Healthfirst Management Services will be reviewed at the e-mail address and phone number supplied. Thank you for considering a career with Healthfirst Management Services.\nEEO Law Poster and Supplement\n\n]]>"
 "Secure our Nation, Ignite your Future\n\nJoin the top Information Technology and Analytic professionals in the industry to make invaluable contributions to our national security on a daily basis. In this innovative, self-contained, Big Data environment, the ManTech team is responsible for everything from infrastructure, to application development, to data science, to advanced analytics and beyond. The team is diverse, the questions are thought-provoking, and the opportunities for growth and advancement are numerous\n\nThe successful candidate will possess a diverse range of data-focused skills and experience, both technical and analytical. They will have a strong desire and capability for problem solving, data analysis and troubleshooting, analytical thinking, and experimentation.\n\nDuties, Tasks & Responsibilities\nWorking with large, complex, and disparate data sets\nDesigning and implementing innovative ways to analyze and exploit the Sponsors data holdings\nResearching and reporting on a wide variety of Sponsor inquiries\nRaising proactive inquiries to the Sponsor based on observations and proposed data analysis/exploitation\nSolving difficult, non-routine problems by applying advanced analytical methodologies, and improving analytic methodologies\nDeveloping custom searches\nCommunicating and coordinating with internal and external partners as needed\nRequired Experience, Skills, & Technologies\n\nThorough knowledge of appropriate analytic tools and methodologies in one or more of the following:\nApplied mathematics (e.g. probability and statistics, formal modeling, computational social sciences)\nComputer programming (e.g. programming languages, math/statistics packages, computer science, machine learning, scientific computing)\nAbility to code or script in one or more general programming language\nExperience with and theoretical understanding of algorithms for classification, regression, clustering, and anomaly detection\nKnowledge of relational databases, including SQL and large-scale distributed systems (e.g. Hadoop)\nExpertise with statistical data analysis (e.g. linear models, multivariate analysis, stochastic models, sampling methods)\nDemonstrated effectiveness in collecting information and accurately representing/visualizing it to non-technical third parties\nTS/SCI with Polygraph\nBachelor of Science or equivalent and 12-15 years related experience, but will consider all levels of experience.\nDesired Experience, Skills & Technologies\nPrevious investigative experience using a combination of technical and analytic skills\n#LI-DU1\n\nManTech International Corporation, as well as its subsidiaries proactively fulfills its role as an equal opportunity employer. We do not discriminate against any employee or applicant for employment because of race, color, sex, religion, age, sexual orientation, gender identity and expression, national origin, marital status, physical or mental disability, status as a Disabled Veteran, Recently Separated Veteran, Active Duty Wartime or Campaign Badge Veteran, Armed Forces Services Medal, or any other characteristic protected by law.\n\nIf you require a reasonable accommodation to apply for a position with ManTech through its online applicant system, please contact ManTech's Corporate EEO Department at (703) 218-6000. ManTech is an affirmative action/equal opportunity employer - minorities, females, disabled and protected veterans are urged to apply. ManTech's utilization of any external recruitment or job placement agency is predicated upon its full compliance with our equal opportunity/affirmative action policies. ManTech does not accept resumes from unsolicited recruiting firms. We pay no fees for unsolicited services.\n\nIf you are a qualified individual with a disability or a disabled veteran, you have the right to request an accommodation if you are unable or limited in your ability to use or access http://www.mantech.com/careers/Pages/careers.aspx as a result of your disability. To request an accommodation please click careers@mantech.com and provide your name and contact information."
 "Overview\n\n\nAnalysis Group is one of the largest international economics consulting firms, with more than 1,000 professionals across 14 offices in North America, Europe, and Asia. Since 1981, we have provided expertise in economics, finance, health care analytics, and strategy to top law firms, Fortune Global 500 companies, and government agencies worldwide. Our internal experts, together with our network of affiliated experts from academia, industry, and government, offer our clients exceptional breadth and depth of expertise.\n\nWe are currently seeking a Data Scientist to join our team. The ideal candidate should be passionate about working on cutting edge research and analytical services for Fortune 500 companies, global pharma/biotech firms and leaders in industries such as finance, energy and life sciences. The Data Scientist will be a contributing member to client engagements and have the opportunity to work with our network of world-class experts and thought leaders.\n\nJob Functions and Responsibilities\n\nThe candidate Data Scientist will help develop, maintain and teach new tools and methodologies related to data science and high performance computing. This position will also help Analysis Group in maintaining our leadership position in terms of advancing methodology and data analytics. The Data Scientist will be responsible for staying abreast of new developments in technology relating to data science, to share more broadly with Analysis Group.\n\nKey responsibilities for this position will include:\nWorking with project teams to address data science/computing challenges\nIdentifying opportunities for technology to enhance service offerings\nActing as a resource and participating in client engagements and research as part of the project team\nMaintaining up-to-date knowledge of computing tools, providing technical training and helping to grow the in-house knowledge base, specifically in a Linux environment\nPresenting research at selected conferences\nExamples of activities for the Data Scientist will include:\nDeveloping data engineering and machine learning production systems for full stack data science projects\nUsing natural language processing methodologies to work with EMR data, social media data and other unstructured data\nOptimizing procedures for managing and accessing large databases (e.g., insurance claims, electronic health records, financial transactions)\nCreating interactive analytics portals and data visualizations (e.g., using R/Shiny, Python/Flask, D3)\nBuilding and maintaining high performance computing (HPC) tools on grid and cloud computing environments\nDeveloping and reviewing software and packages in R, Python and other Object Oriented Languages\nEstablishing optimized procedures for repetitive or computationally intensive tasks (C, C++, Cuda-C)\nQualifications\nStrong credentials and experience in database management and data visualization\nSignificant experience working within a Linux environment required\nBackground in Statistics/Econometrics or Biostatistics\nIdeally PhD in Computer Science, Mathematics, Statistics, Economics or other relevant scientific degree with relevant experience. Other candidates with at least one year of experience in the field may also be considered\nExcellent written and verbal communication skills\nProject experience with R and/or Python\nFamiliar with online/cloud computing/storage (e.g., AWS)\nDemonstrated experience working on project teams and collaborating with others\nSCIENTIFIQUE DES DONNÉES\n\n*L’utilisation du genre masculin sert uniquement à alléger le texte et est utilisé ici en tant que genre neutre\n\nSurvol\n\nGroupe d’analyse ltée est l’une des plus grandes firmes de services-conseils en économie, comptant plus de 950 professionnels répartis dans 14 bureaux en Amérique du Nord, en Europe et en Asie. Depuis 1981, nous offrons notre expertise en matière de stratégie, d’économie, de finance et d’analyse dans le domaine des soins de santé aux grands cabinets d’avocats, aux sociétés Fortune Global 500 et aux agences gouvernementales du monde entier. Nos professionnels en poste conjugués à notre réseau de spécialistes affiliés issus d’universités, d’industries spécifiques et d’organismes gouvernementaux procurent à notre clientèle un savoir-faire d’une portée et d’une profondeur exceptionnelles.\n\nNous sommes présentement à la recherche d'un Scientifique des données (« Data Scientist ») pour se joindre à notre équipe. Le candidat idéal devrait être passionné par la recherche de pointe et les services analytiques pour les entreprises Fortune 500, les entreprises pharmaceutiques et biotechnologiques mondiales et les chefs de file dans des secteurs de la finance, l'énergie et les sciences de la vie. Le Scientifique des données sera un membre contributeur aux mandats des clients et aura l'occasion de travailler avec notre réseau d'experts et de leaders d'opinion de classe mondiale.\n\nDescription du poste et des responsabilités\n\nLe scientifique des données aidera à développer, maintenir et enseigner de nouveaux outils et méthodologies liés à la science des données (« Data Science ») et au HPC. Ce poste aidera également le Groupe d'analyse à maintenir sa position de chef de file en ce qui a trait à l'avancement de la méthodologie et de l'analyse des données. Le scientifique des données sera chargé de se tenir au courant des nouveaux développements technologiques liés à la science des données, afin de les partager plus largement avec le Groupe d'analyse.\n\nLes principales responsabilités de ce poste comprendront:\n\n- Collaborer avec les consultants pour relever les défis de la science des données et de sciences informatiques\n\n- Agir à titre de ressource et participer aux mandats et à la recherche en tant que membre de l'équipe de projet\n\n- Maintenir à jour les connaissances sur les outils informatiques, fournir une formation technique et aider à développer la base de connaissances interne, notamment dans un environnement Linux\n\n- Présenter la recherche à des conférences choisies\n\nExemples de tâches du scientifique des données :\n\n- Développement de systèmes de production en ingénierie des données ainsi qu’en apprentissage machine pour des projets de science des données full stack\n\n- Utiliser des méthodologies NLP pour travailler avec les données médicales électroniques, les données des médias sociaux et d'autres données non structures\n\n- Optimiser les procédures de gestion et d'accès aux grandes bases de données (ex. réclamations d'assurance, dossiers de santé électroniques, transactions financières)\n\n- Création de portails d'analyse interactifs et de visualisations de données (par exemple, en utilisant R/Shiny, Python/Flask, D3)\n\n- Construire et maintenir des outils de calcul de haute performance (HPC).\n\n- Développement et révision de codes en R, Python et autres langages\n\n- Mise en place de procédures optimisées pour les tâches répétitives ou intensives en calcul (C, C++, Cuda-C)\n\nQualifications requises\n\n- Solides références et expérience dans la gestion de bases de données et de la visualisation de données\n\n- Expérience de travail significative dans un environnement Linux requise\n\n- Expérience antérieure en statistique/économétrie ou bio-statistique\n\n- Idéalement, être titulaire d'un doctorat en sciences informatiques, en mathématiques, en statistique, en économie ou d'un autre diplôme scientifique pertinent et posséder une expérience pertinente. Les candidats ayant au moins un an d'expérience dans le domaine peuvent également être considérés.\n\n- Excellentes aptitudes de communication écrite et verbale\n\n- Expérience de projet avec R et/ou Python\n\n- Familiarité avec l'informatique en ligne/info nuagique et le stockage (AWS)\n\n- Expérience de travail démontrée au sein d'équipes de projet et de collaboration avec d'autres personnes\n\n\xad\nEqual Opportunity Employer/Protected Veterans/Individuals with Disabilities.\nPlease view Equal Employment Opportunity Posters provided by OFCCP here.\nThe contractor will not discharge or in any other manner discriminate against employees or applicants because they have inquired about, discussed, or disclosed their own pay or the pay of another employee or applicant. However, employees who have access to the compensation information of other employees or applicants as a part of their essential job functions cannot disclose the pay of other employees or applicants to individuals who do not otherwise have access to compensation information, unless the disclosure is (a) in response to a formal complaint or charge, (b) in furtherance of an investigation, proceeding, hearing, or action, including an investigation conducted by the employer, or (c) consistent with the contractor's legal duty to furnish information. 41 CFR 60-1.35(c)"
 "JOB DESCRIPTION:\n\nDo you have a passion for Data and Machine Learning? Do you dream of working with customers on their most forward-looking AI initiatives? Does the challenge of developing modern machine learning solutions to solve real-world manufacturing problems exciting to you?\n\nWe develop software for monitoring semiconductor manufacturing process and are looking to leverage the latest technologies to address our customer's needs. You will be part of a team that investigates and builds solutions based all the data available in factories, ranging from time series data, to post manufacturing data, to production logs. You will be working side by side with application developers and customers on real world problems with actual manufacturing data.\n\nJOB FUNCTION:\n\nBasic and applied research in statistical machine learning, deep learning, and data science as well as signal and information processing to advance the state of the art in time series analysis of semiconductor manufacturing data.\n\nResponsibilities:\nPerform data analysis, data pre-processing, and feature engineering in support of advanced machine learning algorithm development. Incorporate physical and operational insights/constraints into statistical models to achieve a high degree of robustness.\nPrototype algorithms for proof of concept, validation, and software implementation.\nSupport performance evaluations and the transition of algorithms into existing fault detection and classification systems.\nConvey the results of scientific research to sponsors and the scientific community through briefings, conferences and peer-reviewed publications.\nOther related functions as assigned.\n\nREQUIRED QUALIFICATIONS:\nBachelor's degree in computer science or chemical engineering or related technical field.\nDemonstrated ability in machine learning/artificial intelligence (ML/AI) development and/or scientific modelling and data analysis.\nDemonstrated ability with python/MATLAB or similar abstract language. Experience with both traditional ML and modern deep learning approaches.\nExperience with agile development practices and Git version control.\nExperience with one or more of the DNN frameworks like TensorFlow, PyTorch, Chainer.\nExperience with SQL, Graph stores, or NoSQL stores.\nApplicant must have a dynamic skill set, be willing to work with new technologies, be highly organized and capable of planning and coordinating multiple tasks. The position will require attention to detail, effective problem solving skills and excellent judgment. Ability to work independently with sensitive and confidential information, maintain a professional demeanor, work as a team member without daily supervision.\n\nCOMPENSATION & BENEFITS:\n\nCompensation will be commensurate with experience including a competitive base salary, bonus opportunity, competitive benefits package, and relocation assistance.\n\nINFICON, is committed to ensuring that our online application process provides an equal opportunity to all job seekers that apply without regard to race, religion, ethnicity, national origin, citizenship, gender, age, protected veteran status, disability status, genetic information, sexual orientation, or any other protected characteristic. A notice describing Federal equal employment opportunity laws is available here and here to reaffirm this commitment.\n\nPI120660357"

In [16]:
df["job_description"] = df["job_description"].str.replace("\n", " ",regex=False)
print(df["job_description"].unique()[:5])

["Description  The Senior Data Scientist is responsible for defining, building, and improving statistical models to improve business processes and outcomes in one or more healthcare domains such as Clinical, Enrollment, Claims, and Finance. As part of the broader analytics team, Data Scientist will gather and analyze data to solve and address complex business problems and evaluate scenarios to make predictions on future outcomes and work with the business to communicate and support decision-making. This position requires strong analytical skills and experience in analytic methods including multivariate regressions, hierarchical linear models, regression trees, clustering methods and other complex statistical techniques.  Duties & Responsibilities:  • Develops advanced statistical models to predict, quantify or forecast various operational and performance metrics in multiple healthcare domains • Investigates, recommends, and initiates acquisition of new data resources from internal and external sources • Works with multiple teams to support data collection, integration, and retention requirements based on business needs • Identifies critical and emerging technologies that will support and extend quantitative analytic capabilities • Collaborates with business subject matter experts to select relevant sources of information • Develops expertise with multiple machine learning algorithms and data science techniques, such as exploratory data analysis and predictive modeling, graph theory, recommender systems, text analytics and validation • Develops expertise with Healthfirst datasets, data repositories, and data movement processes • Assists on projects/requests and may lead specific tasks within the project scope • Prepares and manipulates data for use in development of statistical models • Other duties as assigned  Minimum Qualifications:  -Bachelor's Degree  Preferred Qualifications:  - Master’s degree in Computer Science or Statistics Familiarity with major cloud platforms such as AWS and Azure Healthcare Industry Experience  Minimum Qualifications:  -Bachelor's Degree  Preferred Qualifications:  - Master’s degree in Computer Science or Statistics Familiarity with major cloud platforms such as AWS and Azure Healthcare Industry Experience  WE ARE AN EQUAL OPPORTUNITY EMPLOYER. Applicants and employees are considered for positions and are evaluated without regard to mental or physical disability, race, color, religion, gender, national origin, age, genetic information, military or veteran status, sexual orientation, marital status or any other protected Federal, State/Province or Local status unrelated to the performance of the work involved.  If you have a disability under the Americans with Disability Act or a similar law, and want a reasonable accommodation to assist with your job search or application for employment, please contact us by sending an email to careers@Healthfirst.org or calling 212-519-1798 . In your email please include a description of the accommodation you are requesting and a description of the position for which you are applying. Only reasonable accommodation requests related to applying for a position within Healthfirst Management Services will be reviewed at the e-mail address and phone number supplied. Thank you for considering a career with Healthfirst Management Services. EEO Law Poster and Supplement  ]]>"
 "Secure our Nation, Ignite your Future  Join the top Information Technology and Analytic professionals in the industry to make invaluable contributions to our national security on a daily basis. In this innovative, self-contained, Big Data environment, the ManTech team is responsible for everything from infrastructure, to application development, to data science, to advanced analytics and beyond. The team is diverse, the questions are thought-provoking, and the opportunities for growth and advancement are numerous  The successful candidate will possess a diverse range of data-focused skills and experience, both technical and analytical. They will have a strong desire and capability for problem solving, data analysis and troubleshooting, analytical thinking, and experimentation.  Duties, Tasks & Responsibilities Working with large, complex, and disparate data sets Designing and implementing innovative ways to analyze and exploit the Sponsors data holdings Researching and reporting on a wide variety of Sponsor inquiries Raising proactive inquiries to the Sponsor based on observations and proposed data analysis/exploitation Solving difficult, non-routine problems by applying advanced analytical methodologies, and improving analytic methodologies Developing custom searches Communicating and coordinating with internal and external partners as needed Required Experience, Skills, & Technologies  Thorough knowledge of appropriate analytic tools and methodologies in one or more of the following: Applied mathematics (e.g. probability and statistics, formal modeling, computational social sciences) Computer programming (e.g. programming languages, math/statistics packages, computer science, machine learning, scientific computing) Ability to code or script in one or more general programming language Experience with and theoretical understanding of algorithms for classification, regression, clustering, and anomaly detection Knowledge of relational databases, including SQL and large-scale distributed systems (e.g. Hadoop) Expertise with statistical data analysis (e.g. linear models, multivariate analysis, stochastic models, sampling methods) Demonstrated effectiveness in collecting information and accurately representing/visualizing it to non-technical third parties TS/SCI with Polygraph Bachelor of Science or equivalent and 12-15 years related experience, but will consider all levels of experience. Desired Experience, Skills & Technologies Previous investigative experience using a combination of technical and analytic skills #LI-DU1  ManTech International Corporation, as well as its subsidiaries proactively fulfills its role as an equal opportunity employer. We do not discriminate against any employee or applicant for employment because of race, color, sex, religion, age, sexual orientation, gender identity and expression, national origin, marital status, physical or mental disability, status as a Disabled Veteran, Recently Separated Veteran, Active Duty Wartime or Campaign Badge Veteran, Armed Forces Services Medal, or any other characteristic protected by law.  If you require a reasonable accommodation to apply for a position with ManTech through its online applicant system, please contact ManTech's Corporate EEO Department at (703) 218-6000. ManTech is an affirmative action/equal opportunity employer - minorities, females, disabled and protected veterans are urged to apply. ManTech's utilization of any external recruitment or job placement agency is predicated upon its full compliance with our equal opportunity/affirmative action policies. ManTech does not accept resumes from unsolicited recruiting firms. We pay no fees for unsolicited services.  If you are a qualified individual with a disability or a disabled veteran, you have the right to request an accommodation if you are unable or limited in your ability to use or access http://www.mantech.com/careers/Pages/careers.aspx as a result of your disability. To request an accommodation please click careers@mantech.com and provide your name and contact information."
 "Overview   Analysis Group is one of the largest international economics consulting firms, with more than 1,000 professionals across 14 offices in North America, Europe, and Asia. Since 1981, we have provided expertise in economics, finance, health care analytics, and strategy to top law firms, Fortune Global 500 companies, and government agencies worldwide. Our internal experts, together with our network of affiliated experts from academia, industry, and government, offer our clients exceptional breadth and depth of expertise.  We are currently seeking a Data Scientist to join our team. The ideal candidate should be passionate about working on cutting edge research and analytical services for Fortune 500 companies, global pharma/biotech firms and leaders in industries such as finance, energy and life sciences. The Data Scientist will be a contributing member to client engagements and have the opportunity to work with our network of world-class experts and thought leaders.  Job Functions and Responsibilities  The candidate Data Scientist will help develop, maintain and teach new tools and methodologies related to data science and high performance computing. This position will also help Analysis Group in maintaining our leadership position in terms of advancing methodology and data analytics. The Data Scientist will be responsible for staying abreast of new developments in technology relating to data science, to share more broadly with Analysis Group.  Key responsibilities for this position will include: Working with project teams to address data science/computing challenges Identifying opportunities for technology to enhance service offerings Acting as a resource and participating in client engagements and research as part of the project team Maintaining up-to-date knowledge of computing tools, providing technical training and helping to grow the in-house knowledge base, specifically in a Linux environment Presenting research at selected conferences Examples of activities for the Data Scientist will include: Developing data engineering and machine learning production systems for full stack data science projects Using natural language processing methodologies to work with EMR data, social media data and other unstructured data Optimizing procedures for managing and accessing large databases (e.g., insurance claims, electronic health records, financial transactions) Creating interactive analytics portals and data visualizations (e.g., using R/Shiny, Python/Flask, D3) Building and maintaining high performance computing (HPC) tools on grid and cloud computing environments Developing and reviewing software and packages in R, Python and other Object Oriented Languages Establishing optimized procedures for repetitive or computationally intensive tasks (C, C++, Cuda-C) Qualifications Strong credentials and experience in database management and data visualization Significant experience working within a Linux environment required Background in Statistics/Econometrics or Biostatistics Ideally PhD in Computer Science, Mathematics, Statistics, Economics or other relevant scientific degree with relevant experience. Other candidates with at least one year of experience in the field may also be considered Excellent written and verbal communication skills Project experience with R and/or Python Familiar with online/cloud computing/storage (e.g., AWS) Demonstrated experience working on project teams and collaborating with others SCIENTIFIQUE DES DONNÉES  *L’utilisation du genre masculin sert uniquement à alléger le texte et est utilisé ici en tant que genre neutre  Survol  Groupe d’analyse ltée est l’une des plus grandes firmes de services-conseils en économie, comptant plus de 950 professionnels répartis dans 14 bureaux en Amérique du Nord, en Europe et en Asie. Depuis 1981, nous offrons notre expertise en matière de stratégie, d’économie, de finance et d’analyse dans le domaine des soins de santé aux grands cabinets d’avocats, aux sociétés Fortune Global 500 et aux agences gouvernementales du monde entier. Nos professionnels en poste conjugués à notre réseau de spécialistes affiliés issus d’universités, d’industries spécifiques et d’organismes gouvernementaux procurent à notre clientèle un savoir-faire d’une portée et d’une profondeur exceptionnelles.  Nous sommes présentement à la recherche d'un Scientifique des données (« Data Scientist ») pour se joindre à notre équipe. Le candidat idéal devrait être passionné par la recherche de pointe et les services analytiques pour les entreprises Fortune 500, les entreprises pharmaceutiques et biotechnologiques mondiales et les chefs de file dans des secteurs de la finance, l'énergie et les sciences de la vie. Le Scientifique des données sera un membre contributeur aux mandats des clients et aura l'occasion de travailler avec notre réseau d'experts et de leaders d'opinion de classe mondiale.  Description du poste et des responsabilités  Le scientifique des données aidera à développer, maintenir et enseigner de nouveaux outils et méthodologies liés à la science des données (« Data Science ») et au HPC. Ce poste aidera également le Groupe d'analyse à maintenir sa position de chef de file en ce qui a trait à l'avancement de la méthodologie et de l'analyse des données. Le scientifique des données sera chargé de se tenir au courant des nouveaux développements technologiques liés à la science des données, afin de les partager plus largement avec le Groupe d'analyse.  Les principales responsabilités de ce poste comprendront:  - Collaborer avec les consultants pour relever les défis de la science des données et de sciences informatiques  - Agir à titre de ressource et participer aux mandats et à la recherche en tant que membre de l'équipe de projet  - Maintenir à jour les connaissances sur les outils informatiques, fournir une formation technique et aider à développer la base de connaissances interne, notamment dans un environnement Linux  - Présenter la recherche à des conférences choisies  Exemples de tâches du scientifique des données :  - Développement de systèmes de production en ingénierie des données ainsi qu’en apprentissage machine pour des projets de science des données full stack  - Utiliser des méthodologies NLP pour travailler avec les données médicales électroniques, les données des médias sociaux et d'autres données non structures  - Optimiser les procédures de gestion et d'accès aux grandes bases de données (ex. réclamations d'assurance, dossiers de santé électroniques, transactions financières)  - Création de portails d'analyse interactifs et de visualisations de données (par exemple, en utilisant R/Shiny, Python/Flask, D3)  - Construire et maintenir des outils de calcul de haute performance (HPC).  - Développement et révision de codes en R, Python et autres langages  - Mise en place de procédures optimisées pour les tâches répétitives ou intensives en calcul (C, C++, Cuda-C)  Qualifications requises  - Solides références et expérience dans la gestion de bases de données et de la visualisation de données  - Expérience de travail significative dans un environnement Linux requise  - Expérience antérieure en statistique/économétrie ou bio-statistique  - Idéalement, être titulaire d'un doctorat en sciences informatiques, en mathématiques, en statistique, en économie ou d'un autre diplôme scientifique pertinent et posséder une expérience pertinente. Les candidats ayant au moins un an d'expérience dans le domaine peuvent également être considérés.  - Excellentes aptitudes de communication écrite et verbale  - Expérience de projet avec R et/ou Python  - Familiarité avec l'informatique en ligne/info nuagique et le stockage (AWS)  - Expérience de travail démontrée au sein d'équipes de projet et de collaboration avec d'autres personnes  \xad Equal Opportunity Employer/Protected Veterans/Individuals with Disabilities. Please view Equal Employment Opportunity Posters provided by OFCCP here. The contractor will not discharge or in any other manner discriminate against employees or applicants because they have inquired about, discussed, or disclosed their own pay or the pay of another employee or applicant. However, employees who have access to the compensation information of other employees or applicants as a part of their essential job functions cannot disclose the pay of other employees or applicants to individuals who do not otherwise have access to compensation information, unless the disclosure is (a) in response to a formal complaint or charge, (b) in furtherance of an investigation, proceeding, hearing, or action, including an investigation conducted by the employer, or (c) consistent with the contractor's legal duty to furnish information. 41 CFR 60-1.35(c)"
 "JOB DESCRIPTION:  Do you have a passion for Data and Machine Learning? Do you dream of working with customers on their most forward-looking AI initiatives? Does the challenge of developing modern machine learning solutions to solve real-world manufacturing problems exciting to you?  We develop software for monitoring semiconductor manufacturing process and are looking to leverage the latest technologies to address our customer's needs. You will be part of a team that investigates and builds solutions based all the data available in factories, ranging from time series data, to post manufacturing data, to production logs. You will be working side by side with application developers and customers on real world problems with actual manufacturing data.  JOB FUNCTION:  Basic and applied research in statistical machine learning, deep learning, and data science as well as signal and information processing to advance the state of the art in time series analysis of semiconductor manufacturing data.  Responsibilities: Perform data analysis, data pre-processing, and feature engineering in support of advanced machine learning algorithm development. Incorporate physical and operational insights/constraints into statistical models to achieve a high degree of robustness. Prototype algorithms for proof of concept, validation, and software implementation. Support performance evaluations and the transition of algorithms into existing fault detection and classification systems. Convey the results of scientific research to sponsors and the scientific community through briefings, conferences and peer-reviewed publications. Other related functions as assigned.  REQUIRED QUALIFICATIONS: Bachelor's degree in computer science or chemical engineering or related technical field. Demonstrated ability in machine learning/artificial intelligence (ML/AI) development and/or scientific modelling and data analysis. Demonstrated ability with python/MATLAB or similar abstract language. Experience with both traditional ML and modern deep learning approaches. Experience with agile development practices and Git version control. Experience with one or more of the DNN frameworks like TensorFlow, PyTorch, Chainer. Experience with SQL, Graph stores, or NoSQL stores. Applicant must have a dynamic skill set, be willing to work with new technologies, be highly organized and capable of planning and coordinating multiple tasks. The position will require attention to detail, effective problem solving skills and excellent judgment. Ability to work independently with sensitive and confidential information, maintain a professional demeanor, work as a team member without daily supervision.  COMPENSATION & BENEFITS:  Compensation will be commensurate with experience including a competitive base salary, bonus opportunity, competitive benefits package, and relocation assistance.  INFICON, is committed to ensuring that our online application process provides an equal opportunity to all job seekers that apply without regard to race, religion, ethnicity, national origin, citizenship, gender, age, protected veteran status, disability status, genetic information, sexual orientation, or any other protected characteristic. A notice describing Federal equal employment opportunity laws is available here and here to reaffirm this commitment.  PI120660357"

In [17]:
df.head()

,index,job_title,salary_estimate,job_description,rating,company_name,location,headquarters,size,founded,type_of_ownership,industry,sector,revenue,competitors,min_salary,max_salary
0,0,Sr Data Scientist,137000-171000,Description The Senior Data Scientist is resp...,3.1,Healthfirst,"New York, NY","New York, NY",1001 to 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,Unknown / Non-Applicable,"EmblemHealth, UnitedHealth Group, Aetna",137000,171000
1,1,Data Scientist,137000-171000,"Secure our Nation, Ignite your Future Join th...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 to 10000 employees,1968,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),-1,137000,171000
2,2,Data Scientist,137000-171000,Overview Analysis Group is one of the larges...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 to 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,$100 to $500 million (USD),-1,137000,171000
3,3,Data Scientist,137000-171000,JOB DESCRIPTION: Do you have a passion for Da...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 to 1000 employees,2000,Company - Public,Electrical & Electronic Manufacturing,Manufacturing,$100 to $500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",137000,171000
4,4,Data Scientist,137000-171000,Data Scientist Affinity Solutions / Marketing ...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",137000,171000

In [18]:
print(df["rating"].unique())

[ 3.1  4.2  3.8  3.5  2.9  3.9  4.4  3.6  4.5  4.7  3.7  3.4  4.1  3.2
  4.3  2.8  5.   4.8  3.3  2.7  2.2  2.6  4.   2.5  4.9  2.4 -1.   2.3
  4.6  3.   2.1  2. ]

In [19]:
import numpy as np
df["rating"] = df["rating"].replace(-1, np.nan)
print(df["rating"].unique())

[3.1 4.2 3.8 3.5 2.9 3.9 4.4 3.6 4.5 4.7 3.7 3.4 4.1 3.2 4.3 2.8 5.  4.8
 3.3 2.7 2.2 2.6 4.  2.5 4.9 2.4 nan 2.3 4.6 3.  2.1 2. ]

In [20]:
print(df["size"].unique()[:5])

['1001 to 5000 employees' '5001 to 10000 employees'
 '501 to 1000 employees' '51 to 200 employees' '10000+ employees']

In [21]:
df["size"] = df["size"].str.replace("to","_",regex=False)
print(df["size"].unique()[:5])

['1001 _ 5000 employees' '5001 _ 10000 employees' '501 _ 1000 employees'
 '51 _ 200 employees' '10000+ employees']

In [22]:
print(df["founded"].unique())

[1993 1968 1981 2000 1998 2010 1996 1990 1983 2014 2012 2016 1965 1973
 1986 1997 2015 1945 1988 2017 2011 1967 1860 1992 2003 1951 2005 2019
 1925 2008 1999 1978 1966 1912 1958 2013 1849 1781 1926 2006 1994 1863
 1995   -1 1982 1974 2001 1985 1913 1971 1911 2009 1959 2007 1939 2002
 1961 1963 1969 1946 1957 1953 1948 1850 1851 2004 1976 1918 1954 1947
 1955 2018 1937 1917 1935 1929 1820 1952 1932 1894 1960 1788 1830 1984
 1933 1880 1887 1970 1942 1980 1989 1908 1853 1875 1914 1898 1956 1977
 1987 1896 1972 1949 1962]

In [23]:
df["founded"] = df["founded"].replace(-1,np.nan)
print(df["founded"].unique())

[1993. 1968. 1981. 2000. 1998. 2010. 1996. 1990. 1983. 2014. 2012. 2016.
 1965. 1973. 1986. 1997. 2015. 1945. 1988. 2017. 2011. 1967. 1860. 1992.
 2003. 1951. 2005. 2019. 1925. 2008. 1999. 1978. 1966. 1912. 1958. 2013.
 1849. 1781. 1926. 2006. 1994. 1863. 1995.   nan 1982. 1974. 2001. 1985.
 1913. 1971. 1911. 2009. 1959. 2007. 1939. 2002. 1961. 1963. 1969. 1946.
 1957. 1953. 1948. 1850. 1851. 2004. 1976. 1918. 1954. 1947. 1955. 2018.
 1937. 1917. 1935. 1929. 1820. 1952. 1932. 1894. 1960. 1788. 1830. 1984.
 1933. 1880. 1887. 1970. 1942. 1980. 1989. 1908. 1853. 1875. 1914. 1898.
 1956. 1977. 1987. 1896. 1972. 1949. 1962.]

In [24]:
print(df["type_of_ownership"].unique())

['Nonprofit Organization' 'Company - Public' 'Private Practice / Firm'
 'Company - Private' 'Government' 'Subsidiary or Business Segment'
 'Other Organization' '-1' 'Unknown' 'Hospital' 'Self-employed'
 'College / University' 'Contract']

In [25]:
df["type_of_ownership"] = df["type_of_ownership"].replace("-1",np.nan)
print(df["type_of_ownership"].unique())

['Nonprofit Organization' 'Company - Public' 'Private Practice / Firm'
 'Company - Private' 'Government' 'Subsidiary or Business Segment'
 'Other Organization' nan 'Unknown' 'Hospital' 'Self-employed'
 'College / University' 'Contract']

In [26]:
df["type_of_ownership"] = df["type_of_ownership"].str.replace("-","",regex=False)
print(df["type_of_ownership"].unique())

['Nonprofit Organization' 'Company  Public' 'Private Practice / Firm'
 'Company  Private' 'Government' 'Subsidiary or Business Segment'
 'Other Organization' nan 'Unknown' 'Hospital' 'Selfemployed'
 'College / University' 'Contract']

In [27]:
df["type_of_ownership"] = df["type_of_ownership"].str.replace("  "," ",regex=False)
print(df["type_of_ownership"].unique())

['Nonprofit Organization' 'Company Public' 'Private Practice / Firm'
 'Company Private' 'Government' 'Subsidiary or Business Segment'
 'Other Organization' nan 'Unknown' 'Hospital' 'Selfemployed'
 'College / University' 'Contract']

In [28]:
print(df["industry"].unique())

['Insurance Carriers' 'Research & Development' 'Consulting'
 'Electrical & Electronic Manufacturing' 'Advertising & Marketing'
 'Computer Hardware & Software' 'Biotech & Pharmaceuticals'
 'Consumer Electronics & Appliances Stores'
 'Enterprise Software & Network Solutions' 'IT Services' 'Energy'
 'Chemical Manufacturing' 'Federal Agencies' 'Internet'
 'Health Care Services & Hospitals'
 'Investment Banking & Asset Management' 'Aerospace & Defense' 'Utilities'
 '-1' 'Express Delivery Services' 'Staffing & Outsourcing'
 'Insurance Agencies & Brokerages' 'Consumer Products Manufacturing'
 'Industrial Manufacturing' 'Food & Beverage Manufacturing'
 'Banks & Credit Unions' 'Video Games' 'Shipping'
 'Telecommunications Services' 'Lending'
 'Cable, Internet & Telephone Providers' 'Real Estate'
 'Venture Capital & Private Equity' 'Miscellaneous Manufacturing'
 'Oil & Gas Services' 'Transportation Equipment Manufacturing'
 'Telecommunications Manufacturing' 'Transportation Management'
 'News Outlet' 'Architectural & Engineering Services'
 'Food & Beverage Stores' 'Other Retail Stores'
 'Hotels, Motels, & Resorts' 'State & Regional Agencies'
 'Financial Transaction Processing' 'Timber Operations'
 'Colleges & Universities' 'Travel Agencies' 'Accounting'
 'Logistics & Supply Chain' 'Farm Support Services' 'Social Assistance'
 'Construction' 'Department, Clothing, & Shoe Stores' 'Publishing'
 'Health, Beauty, & Fitness' 'Wholesale' 'Rail']

In [29]:
df["industry"] = df["industry"].replace("-1",np.nan)
print(df["industry"].unique())

['Insurance Carriers' 'Research & Development' 'Consulting'
 'Electrical & Electronic Manufacturing' 'Advertising & Marketing'
 'Computer Hardware & Software' 'Biotech & Pharmaceuticals'
 'Consumer Electronics & Appliances Stores'
 'Enterprise Software & Network Solutions' 'IT Services' 'Energy'
 'Chemical Manufacturing' 'Federal Agencies' 'Internet'
 'Health Care Services & Hospitals'
 'Investment Banking & Asset Management' 'Aerospace & Defense' 'Utilities'
 nan 'Express Delivery Services' 'Staffing & Outsourcing'
 'Insurance Agencies & Brokerages' 'Consumer Products Manufacturing'
 'Industrial Manufacturing' 'Food & Beverage Manufacturing'
 'Banks & Credit Unions' 'Video Games' 'Shipping'
 'Telecommunications Services' 'Lending'
 'Cable, Internet & Telephone Providers' 'Real Estate'
 'Venture Capital & Private Equity' 'Miscellaneous Manufacturing'
 'Oil & Gas Services' 'Transportation Equipment Manufacturing'
 'Telecommunications Manufacturing' 'Transportation Management'
 'News Outlet' 'Architectural & Engineering Services'
 'Food & Beverage Stores' 'Other Retail Stores'
 'Hotels, Motels, & Resorts' 'State & Regional Agencies'
 'Financial Transaction Processing' 'Timber Operations'
 'Colleges & Universities' 'Travel Agencies' 'Accounting'
 'Logistics & Supply Chain' 'Farm Support Services' 'Social Assistance'
 'Construction' 'Department, Clothing, & Shoe Stores' 'Publishing'
 'Health, Beauty, & Fitness' 'Wholesale' 'Rail']

In [30]:
print(df["sector"].unique())

['Insurance' 'Business Services' 'Manufacturing' 'Information Technology'
 'Biotech & Pharmaceuticals' 'Retail' 'Oil, Gas, Energy & Utilities'
 'Government' 'Health Care' 'Finance' 'Aerospace & Defense' '-1'
 'Transportation & Logistics' 'Media' 'Telecommunications' 'Real Estate'
 'Travel & Tourism' 'Agriculture & Forestry' 'Education'
 'Accounting & Legal' 'Non-Profit' 'Construction, Repair & Maintenance'
 'Consumer Services']

In [31]:
df["sector"] = df["sector"].replace("-1",np.nan)
print(df["sector"].unique())

['Insurance' 'Business Services' 'Manufacturing' 'Information Technology'
 'Biotech & Pharmaceuticals' 'Retail' 'Oil, Gas, Energy & Utilities'
 'Government' 'Health Care' 'Finance' 'Aerospace & Defense' nan
 'Transportation & Logistics' 'Media' 'Telecommunications' 'Real Estate'
 'Travel & Tourism' 'Agriculture & Forestry' 'Education'
 'Accounting & Legal' 'Non-Profit' 'Construction, Repair & Maintenance'
 'Consumer Services']

In [32]:
print(df["revenue"].unique())

['Unknown / Non-Applicable' '$1 to $2 billion (USD)'
 '$100 to $500 million (USD)' '$10+ billion (USD)'
 '$2 to $5 billion (USD)' '$500 million to $1 billion (USD)'
 '$5 to $10 billion (USD)' '$10 to $25 million (USD)'
 '$25 to $50 million (USD)' '$50 to $100 million (USD)'
 '$1 to $5 million (USD)' '$5 to $10 million (USD)'
 'Less than $1 million (USD)' '-1']

In [33]:
df["revenue"] = df["revenue"].replace("-1",np.nan).str.replace("$","",regex=False)
print(df["revenue"].unique())

['Unknown / Non-Applicable' '1 to 2 billion (USD)'
 '100 to 500 million (USD)' '10+ billion (USD)' '2 to 5 billion (USD)'
 '500 million to 1 billion (USD)' '5 to 10 billion (USD)'
 '10 to 25 million (USD)' '25 to 50 million (USD)'
 '50 to 100 million (USD)' '1 to 5 million (USD)' '5 to 10 million (USD)'
 'Less than 1 million (USD)' nan]

In [34]:
df["revenue"] = df["revenue"].replace("Unknown / Non-Applicable",np.nan)
print(df["revenue"].unique())

[nan '1 to 2 billion (USD)' '100 to 500 million (USD)' '10+ billion (USD)'
 '2 to 5 billion (USD)' '500 million to 1 billion (USD)'
 '5 to 10 billion (USD)' '10 to 25 million (USD)' '25 to 50 million (USD)'
 '50 to 100 million (USD)' '1 to 5 million (USD)' '5 to 10 million (USD)'
 'Less than 1 million (USD)']

In [35]:
print(df["competitors"].unique())

['EmblemHealth, UnitedHealth Group, Aetna' '-1'
 'MKS Instruments, Pfeiffer Vacuum, Agilent Technologies'
 'Commerce Signals, Cardlytics, Yodlee' 'Square, PayPal, H&R Block'
 'Leidos, CACI International, Booz Allen Hamilton'
 'Slalom, Daugherty Business Solutions'
 'Oak Ridge National Laboratory, National Renewable Energy Lab, Los Alamos National Laboratory'
 'CDW, PCM, SHI International'
 'Crossix Solutions Inc., AppNexus, The Trade Desk' 'Northwestern Mutual'
 'Puppet, Ansible, SaltStack'
 'Enlivant, Sunrise Senior Living, Brookdale Senior Living'
 'TrueCar, Cars.com, Kelley Blue Book' 'Travelers, Allstate, State Farm'
 'Novartis, Baxter, Pfizer' 'Skyhigh Networks, Zscaler, NortonLifeLock'
 'Facebook, Google, Pinterest' 'DoorDash, Uber, Grubhub'
 'Munich Re, Hannover RE, SCOR' "IMAGE Skincare, Aveda, Kiehl's"
 'Luxoft, EPAM, Capgemini Invent' 'Sequenom' 'Linqia, Collective Bias'
 'John Deere, Komatsu, CNH Industrial'
 'Thermo Fisher Scientific, Enzymatics, Illumina'
 'CUNA Mutual, SWBC, Overby-Seawell' 'Zola Registry'
 'Colony Specialty, Markel, RLI' 'Roche, GlaxoSmithKline, Novartis'
 'Solution Design Group, Intertech (Minnesota)'
 'Braintree, Authorize.Net, PayPal' 'Nielsen, Zappi, SurveyMonkey'
 'The World Bank, IMF' 'Booz Allen Hamilton, CACI International'
 'Booz Allen Hamilton, SAIC, LMI' 'Epic, CipherHealth'
 'Copper River Shared Services, Chenega Corporation, Deloitte'
 'Battelle, General Atomics, SAIC' 'IQVIA, ICON'
 'Arbella Insurance, Safety Insurance' 'Engagio, Bombora, Terminus'
 'SAIC, Leidos, Northrop Grumman' 'Bosch, Lear Corporation, Faurecia'
 'Covance, ICON' 'Adecco, ManpowerGroup, Allegis Corporation'
 'GE Digital, Palantir Technologies, Uptake' 'PRA Group'
 'Genomic Health, 23andMe, Illumina' 'Bromium, FireEye, Authentic8'
 'Drip, iContact, Mailchimp'
 "Children's Health, Texas Health Resources, Baylor Scott & White Health"
 'Harris, Fibertek' 'Monster Worldwide, CareerBuilder, Craigslist'
 'Los Alamos National Laboratory, Battelle, SRI International'
 'ManTech, Booz Allen Hamilton, Leidos'
 'Lumentum Operations, Keysight Technologies, O-Net Technologies'
 'Square, Amazon, Apple' 'Pfizer, GlaxoSmithKline'
 'DHL Supply Chain, UPS, FedEx'
 'Raytheon Technologies, General Dynamics, MIT Lincoln Laboratory'
 'Eaton, SMC Corporation, Bosch Rexroth'
 'Advisory Board, Booz Allen Hamilton, McKinsey & Company' 'Amazon, Apple'
 'Covidien, Boston Scientific' 'AT&T, Verizon'
 'Los Alamos National Laboratory, NASA Jet Propulsion Laboratory, Sandia National Laboratories'
 'Fluor, Bechtel, AECOM' 'Intertek, SGS, Bureau Veritas'
 'Lockheed Martin, Caterpillar, John Deere'
 'Activision Blizzard, Electronic Arts' 'MediaMath, Conversant, AppNexus'
 'Pfizer, AstraZeneca, Merck' 'Archibus, iOffice, Planon'
 'ACRT Services, Bartlett Tree Experts'
 'TASC, Vencore, Booz Allen Hamilton' 'Seagate Technology, Toshiba'
 'Raytheon Technologies, Northrop Grumman, Booz Allen Hamilton'
 'MIT Lincoln Laboratory, Lockheed Martin, Northrop Grumman'
 'Kforce, PageGroup, Robert Half' 'TEKsystems, Kforce, Randstad US'
 'South Carolina Electric & Gas, Virginia Electric and Power'
 'Cadence Design Systems, Synopsys, Altium Limited'
 'CGI (Nevada), Accenture, Deloitte' 'Accenture, Deloitte, PwC'
 'Bechtel Jacobs, Black & Veatch, HNTB' 'Adecco, Manpower'
 'Acxiom, Merkle, Epsilon (North Carolina)' 'Amazon, Accenture, Microsoft'
 'Booz Allen Hamilton, Deloitte, ERPi'
 'TEKsystems, Insight Global, Accenture' 'H&M, Inditex, Fast Retailing'
 'Novartis, AstraZeneca, Siemens Healthineers' 'Aquent, 24 Seven Talent'
 'Google, Microsoft, Samsung Electronics'
 'AppDynamics, Datadog, Dynatrace'
 'Liberty Mutual Insurance, EMPLOYERS, Travelers'
 'KPMG, Accenture, Deloitte' 'General Atomics, Boeing, Northrop Grumman'
 'Los Alamos National Laboratory, Lawrence Livermore National Laboratory'
 'Cognizant Technology Solutions, Infosys, Wipro' 'Humana'
 'Accenture, Northrop Grumman, Xerox'
 'United Natural Foods, US Foods, DPI Specialty Foods'
 'LivePerson, Salesforce, SAP' 'Zurich Insurance, AXA XL, Allianz'
 'CSC, ManTech, SAIC'
 'Genomic Health, Myriad Genetics, The Broad Institute']

In [36]:
df["competitors"] = df["competitors"].replace("-1",np.nan)
print(df["competitors"].unique())

['EmblemHealth, UnitedHealth Group, Aetna' nan
 'MKS Instruments, Pfeiffer Vacuum, Agilent Technologies'
 'Commerce Signals, Cardlytics, Yodlee' 'Square, PayPal, H&R Block'
 'Leidos, CACI International, Booz Allen Hamilton'
 'Slalom, Daugherty Business Solutions'
 'Oak Ridge National Laboratory, National Renewable Energy Lab, Los Alamos National Laboratory'
 'CDW, PCM, SHI International'
 'Crossix Solutions Inc., AppNexus, The Trade Desk' 'Northwestern Mutual'
 'Puppet, Ansible, SaltStack'
 'Enlivant, Sunrise Senior Living, Brookdale Senior Living'
 'TrueCar, Cars.com, Kelley Blue Book' 'Travelers, Allstate, State Farm'
 'Novartis, Baxter, Pfizer' 'Skyhigh Networks, Zscaler, NortonLifeLock'
 'Facebook, Google, Pinterest' 'DoorDash, Uber, Grubhub'
 'Munich Re, Hannover RE, SCOR' "IMAGE Skincare, Aveda, Kiehl's"
 'Luxoft, EPAM, Capgemini Invent' 'Sequenom' 'Linqia, Collective Bias'
 'John Deere, Komatsu, CNH Industrial'
 'Thermo Fisher Scientific, Enzymatics, Illumina'
 'CUNA Mutual, SWBC, Overby-Seawell' 'Zola Registry'
 'Colony Specialty, Markel, RLI' 'Roche, GlaxoSmithKline, Novartis'
 'Solution Design Group, Intertech (Minnesota)'
 'Braintree, Authorize.Net, PayPal' 'Nielsen, Zappi, SurveyMonkey'
 'The World Bank, IMF' 'Booz Allen Hamilton, CACI International'
 'Booz Allen Hamilton, SAIC, LMI' 'Epic, CipherHealth'
 'Copper River Shared Services, Chenega Corporation, Deloitte'
 'Battelle, General Atomics, SAIC' 'IQVIA, ICON'
 'Arbella Insurance, Safety Insurance' 'Engagio, Bombora, Terminus'
 'SAIC, Leidos, Northrop Grumman' 'Bosch, Lear Corporation, Faurecia'
 'Covance, ICON' 'Adecco, ManpowerGroup, Allegis Corporation'
 'GE Digital, Palantir Technologies, Uptake' 'PRA Group'
 'Genomic Health, 23andMe, Illumina' 'Bromium, FireEye, Authentic8'
 'Drip, iContact, Mailchimp'
 "Children's Health, Texas Health Resources, Baylor Scott & White Health"
 'Harris, Fibertek' 'Monster Worldwide, CareerBuilder, Craigslist'
 'Los Alamos National Laboratory, Battelle, SRI International'
 'ManTech, Booz Allen Hamilton, Leidos'
 'Lumentum Operations, Keysight Technologies, O-Net Technologies'
 'Square, Amazon, Apple' 'Pfizer, GlaxoSmithKline'
 'DHL Supply Chain, UPS, FedEx'
 'Raytheon Technologies, General Dynamics, MIT Lincoln Laboratory'
 'Eaton, SMC Corporation, Bosch Rexroth'
 'Advisory Board, Booz Allen Hamilton, McKinsey & Company' 'Amazon, Apple'
 'Covidien, Boston Scientific' 'AT&T, Verizon'
 'Los Alamos National Laboratory, NASA Jet Propulsion Laboratory, Sandia National Laboratories'
 'Fluor, Bechtel, AECOM' 'Intertek, SGS, Bureau Veritas'
 'Lockheed Martin, Caterpillar, John Deere'
 'Activision Blizzard, Electronic Arts' 'MediaMath, Conversant, AppNexus'
 'Pfizer, AstraZeneca, Merck' 'Archibus, iOffice, Planon'
 'ACRT Services, Bartlett Tree Experts'
 'TASC, Vencore, Booz Allen Hamilton' 'Seagate Technology, Toshiba'
 'Raytheon Technologies, Northrop Grumman, Booz Allen Hamilton'
 'MIT Lincoln Laboratory, Lockheed Martin, Northrop Grumman'
 'Kforce, PageGroup, Robert Half' 'TEKsystems, Kforce, Randstad US'
 'South Carolina Electric & Gas, Virginia Electric and Power'
 'Cadence Design Systems, Synopsys, Altium Limited'
 'CGI (Nevada), Accenture, Deloitte' 'Accenture, Deloitte, PwC'
 'Bechtel Jacobs, Black & Veatch, HNTB' 'Adecco, Manpower'
 'Acxiom, Merkle, Epsilon (North Carolina)' 'Amazon, Accenture, Microsoft'
 'Booz Allen Hamilton, Deloitte, ERPi'
 'TEKsystems, Insight Global, Accenture' 'H&M, Inditex, Fast Retailing'
 'Novartis, AstraZeneca, Siemens Healthineers' 'Aquent, 24 Seven Talent'
 'Google, Microsoft, Samsung Electronics'
 'AppDynamics, Datadog, Dynatrace'
 'Liberty Mutual Insurance, EMPLOYERS, Travelers'
 'KPMG, Accenture, Deloitte' 'General Atomics, Boeing, Northrop Grumman'
 'Los Alamos National Laboratory, Lawrence Livermore National Laboratory'
 'Cognizant Technology Solutions, Infosys, Wipro' 'Humana'
 'Accenture, Northrop Grumman, Xerox'
 'United Natural Foods, US Foods, DPI Specialty Foods'
 'LivePerson, Salesforce, SAP' 'Zurich Insurance, AXA XL, Allianz'
 'CSC, ManTech, SAIC'
 'Genomic Health, Myriad Genetics, The Broad Institute']

In [37]:
df.head()

,index,job_title,salary_estimate,job_description,rating,company_name,location,headquarters,size,founded,type_of_ownership,industry,sector,revenue,competitors,min_salary,max_salary
0,0,Sr Data Scientist,137000-171000,Description The Senior Data Scientist is resp...,3.1,Healthfirst,"New York, NY","New York, NY",1001 _ 5000 employees,1993.0,Nonprofit Organization,Insurance Carriers,Insurance,NaN,"EmblemHealth, UnitedHealth Group, Aetna",137000,171000
1,1,Data Scientist,137000-171000,"Secure our Nation, Ignite your Future Join th...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 _ 10000 employees,1968.0,Company Public,Research & Development,Business Services,1 to 2 billion (USD),NaN,137000,171000
2,2,Data Scientist,137000-171000,Overview Analysis Group is one of the larges...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 _ 5000 employees,1981.0,Private Practice / Firm,Consulting,Business Services,100 to 500 million (USD),NaN,137000,171000
3,3,Data Scientist,137000-171000,JOB DESCRIPTION: Do you have a passion for Da...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 _ 1000 employees,2000.0,Company Public,Electrical & Electronic Manufacturing,Manufacturing,100 to 500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech...",137000,171000
4,4,Data Scientist,137000-171000,Data Scientist Affinity Solutions / Marketing ...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 _ 200 employees,1998.0,Company Private,Advertising & Marketing,Business Services,NaN,"Commerce Signals, Cardlytics, Yodlee",137000,171000

In [38]:
print(df.columns.tolist())

['index', 'job_title', 'salary_estimate', 'job_description', 'rating', 'company_name', 'location', 'headquarters', 'size', 'founded', 'type_of_ownership', 'industry', 'sector', 'revenue', 'competitors', 'min_salary', 'max_salary']

In [39]:
df = df.drop(columns=["salary_estimate"])
df["founded"] = df["founded"].astype("Int64")

In [40]:
print(df.columns.tolist())

['index', 'job_title', 'job_description', 'rating', 'company_name', 'location', 'headquarters', 'size', 'founded', 'type_of_ownership', 'industry', 'sector', 'revenue', 'competitors', 'min_salary', 'max_salary']

In [41]:
df = df[["index","job_title", "min_salary", "max_salary", "job_description", "rating", "company_name", "location", "headquarters", "size", "founded", "type_of_ownership", "industry", "sector", "revenue", "competitors"]]

In [42]:
df.head()

,index,job_title,min_salary,max_salary,job_description,rating,company_name,location,headquarters,size,founded,type_of_ownership,industry,sector,revenue,competitors
0,0,Sr Data Scientist,137000,171000,Description The Senior Data Scientist is resp...,3.1,Healthfirst,"New York, NY","New York, NY",1001 _ 5000 employees,1993,Nonprofit Organization,Insurance Carriers,Insurance,NaN,"EmblemHealth, UnitedHealth Group, Aetna"
1,1,Data Scientist,137000,171000,"Secure our Nation, Ignite your Future Join th...",4.2,ManTech,"Chantilly, VA","Herndon, VA",5001 _ 10000 employees,1968,Company Public,Research & Development,Business Services,1 to 2 billion (USD),NaN
2,2,Data Scientist,137000,171000,Overview Analysis Group is one of the larges...,3.8,Analysis Group,"Boston, MA","Boston, MA",1001 _ 5000 employees,1981,Private Practice / Firm,Consulting,Business Services,100 to 500 million (USD),NaN
3,3,Data Scientist,137000,171000,JOB DESCRIPTION: Do you have a passion for Da...,3.5,INFICON,"Newton, MA","Bad Ragaz, Switzerland",501 _ 1000 employees,2000,Company Public,Electrical & Electronic Manufacturing,Manufacturing,100 to 500 million (USD),"MKS Instruments, Pfeiffer Vacuum, Agilent Tech..."
4,4,Data Scientist,137000,171000,Data Scientist Affinity Solutions / Marketing ...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 _ 200 employees,1998,Company Private,Advertising & Marketing,Business Services,NaN,"Commerce Signals, Cardlytics, Yodlee"

In [43]:
import openpyxl
from openpyxl import load_workbook
from openpyxl.utils import get_column_letter

df.to_excel("data cleaning.xlsx", index = False)

wb = load_workbook("data cleaning.xlsx")
ws = wb.active

for col in ws.columns:
    ws.column_dimensions[get_column_letter(col[0].column)].width = 20

wb.save("data cleaning.xlsx")